---
abstract: 'write DOAP data quickly and easily'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.015, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-DOAP-Lite
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  RDF::DOAP::Lite:
    file: lib/RDF/DOAP/Lite.pm
    version: 0.002
recommends:
  CPAN::Changes: 0
requires:
  CPAN::Meta: 2.110320
  Scalar::Util: 1.24
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/RDF-DOAP-Lite/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=RDF-DOAP-Lite
  homepage: https://metacpan.org/release/RDF-DOAP-Lite
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-rdf-doap-lite.git
version: 0.002
x_provides_scripts:
  cpan2doap:
    file: bin/cpan2doap
